# add bpm to prometheus2
- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: bpm
    release: bpm

- type: replace
  path: /releases/-
  value:
    name: bpm
    version: 1.1.8
    url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.8
    sha1: c956394fce7e74f741e4ae8c256b480904ad5942
